spring:
  config:
    activate:
      on-profile: dev

  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show_sql: true
    properties:
      hibernate:
        use_sql_comments: false
        format_sql: true
        default_batch_fetch_size: 1000
    open-in-view: false
    generate-ddl: false

  datasource:
    hikari:
      jdbc-url: jdbc:mysql://127.0.0.1:3306/githubrate?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
      username: root
      password: alrtm1324!
      driver-class-name: com.mysql.cj.jdbc.Driver


  flyway:
    enabled: true
    baseline-on-migrate: true

