spring:
  config:
    activate:
      on-profile: local

  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb;MODE=Oracle
    hikari:
      jdbc-url: jdbc:h2:mem:testdb

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show_sql: true
    properties:
      hibernate:
        use_sql_comments: false
        format_sql: true
        default_batch_fetch_size: 1000
    open-in-view: false

springdoc:
  api-docs:
    version: openapi_3_0
    path: /public-api/api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /public-api/swagger-ui
    disable-swagger-default-url: true
    display-request-duration: true
  paths-to-match:
    - /**

